### ISSUE TITLE
Use tax_address instead of ship_address?

### ISSUE THREAD

**Issue by handerson** [spree-contrib/spree_tax_cloud#27]
I have a situation where I need to provide estimated sales tax for orders before a shipping address has been entered based on a user provided postal code. If Spree::TaxCloud used an order's tax_address instead of its ship_address I could override or redefine the tax_address method to return the postal code-based address without touching the shipping or billing address.

**Comment by brchristian** [comment]
@handerson It was my understanding based on conversations with the TaxCloud CEO that because in US sales tax is only shipping-address-based, that they only want their API to be able to be used that way. If @JDutil or someone from Spree wants to weigh in and override that, then I'm open to that conversation, but otherwise the use of ship_address rather than tax_address was a deliberate choice. Perhaps you can get the behavior that you want just as easily by overriding shipping_address, rather than tax_address?

**Comment by handerson** [comment]
@brchristian Thanks for the quick reply. That makes sense. My concern with overriding shipping address is that it might have unintended consequences (either now or in the future). By using the tax address I was hoping to limit the effects to just taxes.

As far as I can tell everything still works as expected when I override ship_address, so I'll go that direction unless you decide to incorporate tax_address. Thanks again!

**Comment by JDutil** [comment]
Tax address is there to enable these sort of customizations, however by doing so you open up the possibility for people to misuse it purposefully or unintentionally.  So it would probably be fine to use it, but at the same time it's also probably wiser to leave as is to prevent people from messing things up.

**Comment by brchristian** [comment]
@handerson Makes sense to be cautious about the override but I'm glad to hear that using ship_address seems to be working. For now based on the feedback from Jeff Dutil at Spree and David Campbell at TaxCloud it sounds like it's best to leave the extension as is, so I'm going to go ahead and close this issue for now. If this turns out to be a consistent request for other users, or if ship_address is causing unanticipated havoc we can always revisit.
